Prevent pa11y fails from failing the job step and not running the script

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -86,7 +86,20 @@ jobs:
             - run:
                 name: Run full pa11y scan
                 command: |
+                  set +e
                   ./serve-pa11yci && npm run pa11y-sitemap 2> >(tee pa11y-errors >&2)
+                  if [[ $PIPESTATUS -eq 2 ]]; then
+                    set +o history
+                    JSON=$(echo '{"event_type":"failed-pa11y-scan","client_payload":{"report":"'"$(cat pa11y-errors | base64 -w0)"'"}}' | jq -c -r '.|tojson')
+                    curl -L \
+                    -X POST \
+                    -H "Accept: application/vnd.github+json" \
+                    -H "Authorization: Bearer $GITHUB_TEST_TOKEN" \
+                    -H "X-GitHub-Api-Version: 2022-11-28" \
+                    https://api.github.com/repos/18f/18f.gsa.gov/dispatches \
+                    -d $JSON
+                    set -o history
+                  fi
       # When someone pushes to a branch on GitHub with an open pull request
       # it makes a webhook POST to CircleCI that satisfies this condition
       - when:
@@ -105,7 +118,7 @@ workflows:
       - schedule:
           # Run nightly at 10am UTC / 5am ET
           #cron: "59 9 * * *"
-          cron: "12 * * * *"
+          cron: "37 * * * *"
           filters:
             branches:
               only:
