Tweak the config file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,8 +49,10 @@ jobs:
           # needed, a full site scan does not use the pa11y_targets file
           command: |
             bundle exec jekyll build
-            echo "export PA11Y_TARGETS=$(cat pa11y_targets | base64 --wrap=0)" >> "$BASH_ENV"
-            source "$BASH_ENV"
+            if test -f pa11y_targets; then
+              echo "export PA11Y_TARGETS=$(cat pa11y_targets | base64 --wrap=0)" >> "$BASH_ENV"
+              source "$BASH_ENV"
+            fi
       - run: npm run htmlproofer
       - run:
           name: Run rspec
@@ -72,14 +74,20 @@ jobs:
           steps:
             - run:
                 name: Run pa11y scan on changed files
-                command: npm run pa11y-ci -- $(echo $PA11Y_TARGETS | base64 --decode)
+                command: |
+                  if [[ -z $"{PA11Y_TARGETS}" ]]; then
+                    npm run pa11y-ci -- $(echo $PA11Y_TARGETS | base64 --decode)
+                  else
+                    echo "The pa11y targets environment variable was not found, no pa11y scan performed."
+                    exit 1
+                  fi
 workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           # Run nightly at 10am UTC / 5am ET
-          cron: "20 * * * *"
+          cron: "10 * * * *"
           filters:
             branches:
               only:
