Testing GitHub webhook call

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,7 @@
 version: 2.1
 
+orbs:
+  jq: circleci/jq@3.0.0
 jobs:
  build:
     docker:
@@ -9,6 +11,8 @@ jobs:
       LANGUAGE: "en_US.UTF-8"
       LC_ALL: "en_US.UTF-8"
     steps:
+      - jq/install:
+          version: jq-1.7
       - run:
           name: Fix locales
           command: |
@@ -81,7 +85,20 @@ jobs:
           steps:
             - run:
                 name: Run full pa11y scan
-                command: ./serve-pa11yci && npm run pa11y-sitemap
+                command: |
+                  ./serve-pa11yci && npm run pa11y-sitemap 2> >(tee pa11y-errors >&2)
+                  if [[ $PIPESTATUS -eq 2 ]]; then
+                    set +o history
+                    JSON=$(echo '{"event_type":"failed-pa11y-scan","client_payload":{"report":"'"$(cat pa11y-errors | base64)"'"}}' | jq -c -r '.|tojson')
+                    curl -L \
+                    -X POST \
+                    -H "Accept: application/vnd.github+json" \
+                    -H "Authorization: Bearer $GITHUB_TEST_TOKEN" \
+                    -H "X-GitHub-Api-Version: 2022-11-28" \
+                    https://api.github.com/repos/18f/18f.gsa.gov/dispatches \
+                    -d $JSON
+                    set -o history
+                  fi
       # When someone pushes to a branch on GitHub with an open pull request
       # it makes a webhook POST to CircleCI that satisfies this condition
       - when:
@@ -99,7 +116,8 @@ workflows:
     triggers:
       - schedule:
           # Run nightly at 10am UTC / 5am ET
-          cron: "59 9 * * *"
+          #cron: "59 9 * * *"
+          cron "5 * * * *"
           filters:
             branches:
               only:
